php /Users/jjmaceda/Documents/proyectos/craiglist-tool/protected/yiic jobs init --index=0 --xml='test_35.xml'
php /Users/jjmaceda/Documents/proyectos/craiglist-tool/protected/yiic jobs init --index=1 --xml='test_35.xml'
php /Users/jjmaceda/Documents/proyectos/craiglist-tool/protected/yiic jobs init --index=2 --xml='test_35.xml'
php /Users/jjmaceda/Documents/proyectos/craiglist-tool/protected/yiic jobs init --index=3 --xml='test_35.xml'
php /Users/jjmaceda/Documents/proyectos/craiglist-tool/protected/yiic jobs init --index=4 --xml='test_35.xml'
php /Users/jjmaceda/Documents/proyectos/craiglist-tool/protected/yiic jobs retryPosts --file='test_35'
