<?php

class Array_areas {

    public static function getAreas() {
        return array(
            array('area_code' => '318', 'area_label' => 'aberdeen'),
            array('area_code' => '364', 'area_label' => 'abilene'),
            array('area_code' => '512', 'area_label' => 'acapulco'),
            array('area_code' => '68', 'area_label' => 'adelaide'),
            array('area_code' => '450', 'area_label' => 'ahmedabad'),
            array('area_code' => '251', 'area_label' => 'akron-canton'),
            array('area_code' => '637', 'area_label' => 'albany, GA'),
            array('area_code' => '59', 'area_label' => 'albany, NY'),
            array('area_code' => '50', 'area_label' => 'albuquerque'),
            array('area_code' => '533', 'area_label' => 'alicante'),
            array('area_code' => '355', 'area_label' => 'altoona-johnstown'),
            array('area_code' => '269', 'area_label' => 'amarillo'),
            array('area_code' => '445', 'area_label' => 'ames, IA'),
            array('area_code' => '82', 'area_label' => 'amsterdam-randstad'),
            array('area_code' => '51', 'area_label' => 'anchorage-mat-su'),
            array('area_code' => '172', 'area_label' => 'ann arbor'),
            array('area_code' => '460', 'area_label' => 'annapolis'),
            array('area_code' => '243', 'area_label' => 'appleton-oshkosh-FDL'),
            array('area_code' => '171', 'area_label' => 'asheville'),
            array('area_code' => '700', 'area_label' => 'ashtabula'),
            array('area_code' => '258', 'area_label' => 'athens, GA'),
            array('area_code' => '438', 'area_label' => 'athens, OH'),
            array('area_code' => '14', 'area_label' => 'atlanta'),
            array('area_code' => '372', 'area_label' => 'auburn'),
            array('area_code' => '69', 'area_label' => 'auckland, NZ'),
            array('area_code' => '256', 'area_label' => 'augusta'),
            array('area_code' => '15', 'area_label' => 'austin'),
            array('area_code' => '606', 'area_label' => 'bacolod'),
            array('area_code' => '406', 'area_label' => 'baja california sur'),
            array('area_code' => '63', 'area_label' => 'bakersfield'),
            array('area_code' => '534', 'area_label' => 'baleares'),
            array('area_code' => '34', 'area_label' => 'baltimore'),
            array('area_code' => '84', 'area_label' => 'bangalore'),
            array('area_code' => '295', 'area_label' => 'bangladesh'),
            array('area_code' => '83', 'area_label' => 'barcelona'),
            array('area_code' => '389', 'area_label' => 'barrie'),
            array('area_code' => '528', 'area_label' => 'basel'),
            array('area_code' => '494', 'area_label' => 'bath'),
            array('area_code' => '199', 'area_label' => 'baton rouge'),
            array('area_code' => '628', 'area_label' => 'battle creek'),
            array('area_code' => '264', 'area_label' => 'beaumont-port arthur'),
            array('area_code' => '154', 'area_label' => 'beijing'),
            array('area_code' => '296', 'area_label' => 'beirut, lebanon'),
            array('area_code' => '115', 'area_label' => 'belfast'),
            array('area_code' => '109', 'area_label' => 'belgium'),
            array('area_code' => '483', 'area_label' => 'belleville, ON'),
            array('area_code' => '217', 'area_label' => 'bellingham'),
            array('area_code' => '513', 'area_label' => 'belo horizonte'),
            array('area_code' => '663', 'area_label' => 'bemidji'),
            array('area_code' => '233', 'area_label' => 'bend'),
            array('area_code' => '108', 'area_label' => 'berlin'),
            array('area_code' => '529', 'area_label' => 'bern'),
            array('area_code' => '612', 'area_label' => 'bhubaneswar'),
            array('area_code' => '609', 'area_label' => 'bicol region'),
            array('area_code' => '535', 'area_label' => 'bilbao'),
            array('area_code' => '657', 'area_label' => 'billings'),
            array('area_code' => '248', 'area_label' => 'binghamton'),
            array('area_code' => '72', 'area_label' => 'birmingham-west mids'),
            array('area_code' => '127', 'area_label' => 'birmingham, AL'),
            array('area_code' => '666', 'area_label' => 'bismarck'),
            array('area_code' => '229', 'area_label' => 'bloomington, IN'),
            array('area_code' => '344', 'area_label' => 'bloomington-normal'),
            array('area_code' => '52', 'area_label' => 'boise'),
            array('area_code' => '578', 'area_label' => 'bolivia'),
            array('area_code' => '396', 'area_label' => 'bologna'),
            array('area_code' => '446', 'area_label' => 'boone'),
            array('area_code' => '412', 'area_label' => 'bordeaux'),
            array('area_code' => '4', 'area_label' => 'boston'),
            array('area_code' => '319', 'area_label' => 'boulder'),
            array('area_code' => '342', 'area_label' => 'bowling green'),
            array('area_code' => '658', 'area_label' => 'bozeman'),
            array('area_code' => '664', 'area_label' => 'brainerd'),
            array('area_code' => '626', 'area_label' => 'brantford-woodstock'),
            array('area_code' => '514', 'area_label' => 'brasilia'),
            array('area_code' => '522', 'area_label' => 'bremen'),
            array('area_code' => '398', 'area_label' => 'brighton'),
            array('area_code' => '66', 'area_label' => 'brisbane'),
            array('area_code' => '117', 'area_label' => 'bristol'),
            array('area_code' => '526', 'area_label' => 'brittany'),
            array('area_code' => '266', 'area_label' => 'brownsville'),
            array('area_code' => '570', 'area_label' => 'brunswick, GA'),
            array('area_code' => '153', 'area_label' => 'budapest'),
            array('area_code' => '114', 'area_label' => 'buenos aires'),
            array('area_code' => '40', 'area_label' => 'buffalo'),
            array('area_code' => '584', 'area_label' => 'bulgaria'),
            array('area_code' => '661', 'area_label' => 'butte'),
            array('area_code' => '536', 'area_label' => 'cadiz'),
            array('area_code' => '604', 'area_label' => 'cagayan de oro'),
            array('area_code' => '592', 'area_label' => 'cairns'),
            array('area_code' => '77', 'area_label' => 'calgary'),
            array('area_code' => '312', 'area_label' => 'cambridge, UK'),
            array('area_code' => '537', 'area_label' => 'canarias'),
            array('area_code' => '489', 'area_label' => 'canberra'),
            array('area_code' => '239', 'area_label' => 'cape cod-islands'),
            array('area_code' => '136', 'area_label' => 'cape town'),
            array('area_code' => '116', 'area_label' => 'cardiff-wales'),
            array('area_code' => '299', 'area_label' => 'caribbean islands'),
            array('area_code' => '621', 'area_label' => 'cariboo'),
            array('area_code' => '451', 'area_label' => 'catskills'),
            array('area_code' => '548', 'area_label' => 'cebu'),
            array('area_code' => '340', 'area_label' => 'cedar rapids'),
            array('area_code' => '644', 'area_label' => 'central louisiana'),
            array('area_code' => '434', 'area_label' => 'central michigan'),
            array('area_code' => '349', 'area_label' => 'central NJ'),
            array('area_code' => '190', 'area_label' => 'champaign urbana'),
            array('area_code' => '610', 'area_label' => 'chandigarh'),
            array('area_code' => '128', 'area_label' => 'charleston, SC'),
            array('area_code' => '439', 'area_label' => 'charleston, WV'),
            array('area_code' => '41', 'area_label' => 'charlotte'),
            array('area_code' => '290', 'area_label' => 'charlottesville'),
            array('area_code' => '484', 'area_label' => 'chatham-kent'),
            array('area_code' => '220', 'area_label' => 'chattanooga'),
            array('area_code' => '452', 'area_label' => 'chautauqua'),
            array('area_code' => '602', 'area_label' => 'chengdu'),
            array('area_code' => '182', 'area_label' => 'chennai (madras)'),
            array('area_code' => '11', 'area_label' => 'chicago'),
            array('area_code' => '187', 'area_label' => 'chico'),
            array('area_code' => '505', 'area_label' => 'chihuahua'),
            array('area_code' => '158', 'area_label' => 'chile'),
            array('area_code' => '701', 'area_label' => 'chillicothe'),
            array('area_code' => '601', 'area_label' => 'chongqing'),
            array('area_code' => '301', 'area_label' => 'christchurch'),
            array('area_code' => '35', 'area_label' => 'cincinnati, OH'),
            array('area_code' => '511', 'area_label' => 'ciudad juarez'),
            array('area_code' => '465', 'area_label' => 'clarksville, TN'),
            array('area_code' => '27', 'area_label' => 'cleveland'),
            array('area_code' => '653', 'area_label' => 'clovis/portales'),
            array('area_code' => '326', 'area_label' => 'college station'),
            array('area_code' => '313', 'area_label' => 'cologne'),
            array('area_code' => '393', 'area_label' => 'colombia'),
            array('area_code' => '210', 'area_label' => 'colorado springs'),
            array('area_code' => '222', 'area_label' => 'columbia/jeff city'),
            array('area_code' => '101', 'area_label' => 'columbia, SC'),
            array('area_code' => '343', 'area_label' => 'columbus, GA'),
            array('area_code' => '42', 'area_label' => 'columbus, OH'),
            array('area_code' => '473', 'area_label' => 'comox valley'),
            array('area_code' => '670', 'area_label' => 'cookeville'),
            array('area_code' => '107', 'area_label' => 'copenhagen'),
            array('area_code' => '481', 'area_label' => 'cornwall, ON'),
            array('area_code' => '265', 'area_label' => 'corpus christi'),
            array('area_code' => '350', 'area_label' => 'corvallis/albany'),
            array('area_code' => '179', 'area_label' => 'costa rica'),
            array('area_code' => '495', 'area_label' => 'coventry'),
            array('area_code' => '546', 'area_label' => 'croatia'),
            array('area_code' => '705', 'area_label' => 'cumberland valley'),
            array('area_code' => '517', 'area_label' => 'curitiba'),
            array('area_code' => '600', 'area_label' => 'dalian'),
            array('area_code' => '21', 'area_label' => 'dallas/fort worth'),
            array('area_code' => '367', 'area_label' => 'danville'),
            array('area_code' => '491', 'area_label' => 'darwin'),
            array('area_code' => '547', 'area_label' => 'davao city'),
            array('area_code' => '131', 'area_label' => 'dayton/springfield'),
            array('area_code' => '238', 'area_label' => 'daytona beach'),
            array('area_code' => '569', 'area_label' => 'decatur, IL'),
            array('area_code' => '645', 'area_label' => 'deep east texas'),
            array('area_code' => '647', 'area_label' => 'del rio/eagle pass'),
            array('area_code' => '193', 'area_label' => 'delaware'),
            array('area_code' => '86', 'area_label' => 'delhi'),
            array('area_code' => '13', 'area_label' => 'denver'),
            array('area_code' => '496', 'area_label' => 'derby'),
            array('area_code' => '98', 'area_label' => 'des moines'),
            array('area_code' => '22', 'area_label' => 'detroit metro'),
            array('area_code' => '399', 'area_label' => 'devon &amp; cornwall'),
            array('area_code' => '617', 'area_label' => 'dominican republic'),
            array('area_code' => '467', 'area_label' => 'dothan, AL'),
            array('area_code' => '521', 'area_label' => 'dresden'),
            array('area_code' => '74', 'area_label' => 'dublin'),
            array('area_code' => '362', 'area_label' => 'dubuque'),
            array('area_code' => '255', 'area_label' => 'duluth/superior'),
            array('area_code' => '498', 'area_label' => 'dundee'),
            array('area_code' => '594', 'area_label' => 'dunedin'),
            array('area_code' => '303', 'area_label' => 'durban'),
            array('area_code' => '418', 'area_label' => 'dusseldorf'),
            array('area_code' => '402', 'area_label' => 'east anglia'),
            array('area_code' => '424', 'area_label' => 'east idaho'),
            array('area_code' => '400', 'area_label' => 'east midlands'),
            array('area_code' => '322', 'area_label' => 'east oregon'),
            array('area_code' => '713', 'area_label' => 'eastern CO'),
            array('area_code' => '281', 'area_label' => 'eastern CT'),
            array('area_code' => '674', 'area_label' => 'eastern kentucky'),
            array('area_code' => '192', 'area_label' => 'eastern montana'),
            array('area_code' => '335', 'area_label' => 'eastern NC'),
            array('area_code' => '444', 'area_label' => 'eastern panhandle'),
            array('area_code' => '328', 'area_label' => 'eastern shore'),
            array('area_code' => '242', 'area_label' => 'eau claire'),
            array('area_code' => '545', 'area_label' => 'ecuador'),
            array('area_code' => '75', 'area_label' => 'edinburgh'),
            array('area_code' => '78', 'area_label' => 'edmonton'),
            array('area_code' => '162', 'area_label' => 'egypt'),
            array('area_code' => '132', 'area_label' => 'el paso'),
            array('area_code' => '587', 'area_label' => 'el salvador'),
            array('area_code' => '652', 'area_label' => 'elko'),
            array('area_code' => '453', 'area_label' => 'elmira-corning'),
            array('area_code' => '275', 'area_label' => 'erie, PA'),
            array('area_code' => '523', 'area_label' => 'essen/ruhr'),
            array('area_code' => '497', 'area_label' => 'essex'),
            array('area_code' => '576', 'area_label' => 'ethiopia'),
            array('area_code' => '94', 'area_label' => 'eugene'),
            array('area_code' => '227', 'area_label' => 'evansville'),
            array('area_code' => '677', 'area_label' => 'fairbanks'),
            array('area_code' => '435', 'area_label' => 'fargo/moorhead'),
            array('area_code' => '568', 'area_label' => 'farmington, NM'),
            array('area_code' => '542', 'area_label' => 'faro/algarve'),
            array('area_code' => '293', 'area_label' => 'fayetteville, AR'),
            array('area_code' => '273', 'area_label' => 'fayetteville, NC'),
            array('area_code' => '685', 'area_label' => 'finger lakes'),
            array('area_code' => '145', 'area_label' => 'finland'),
            array('area_code' => '244', 'area_label' => 'flagstaff/sedona'),
            array('area_code' => '259', 'area_label' => 'flint'),
            array('area_code' => '560', 'area_label' => 'florence/muscle shoals'),
            array('area_code' => '152', 'area_label' => 'florence/tuscany'),
            array('area_code' => '464', 'area_label' => 'florence, SC'),
            array('area_code' => '330', 'area_label' => 'florida keys'),
            array('area_code' => '287', 'area_label' => 'fort collins/north CO'),
            array('area_code' => '693', 'area_label' => 'fort dodge'),
            array('area_code' => '358', 'area_label' => 'fort smith, AR'),
            array('area_code' => '226', 'area_label' => 'fort wayne'),
            array('area_code' => '518', 'area_label' => 'fortaleza'),
            array('area_code' => '141', 'area_label' => 'frankfurt'),
            array('area_code' => '471', 'area_label' => 'fraser valley'),
            array('area_code' => '633', 'area_label' => 'frederick'),
            array('area_code' => '457', 'area_label' => 'fredericksburg'),
            array('area_code' => '43', 'area_label' => 'fresno/madera'),
            array('area_code' => '477', 'area_label' => 'ft mcmurray'),
            array('area_code' => '125', 'area_label' => 'ft myers/SW florida'),
            array('area_code' => '503', 'area_label' => 'fukuoka'),
            array('area_code' => '559', 'area_label' => 'gadsden-anniston'),
            array('area_code' => '219', 'area_label' => 'gainesville'),
            array('area_code' => '470', 'area_label' => 'galveston'),
            array('area_code' => '146', 'area_label' => 'geneva'),
            array('area_code' => '531', 'area_label' => 'genoa'),
            array('area_code' => '575', 'area_label' => 'ghana'),
            array('area_code' => '73', 'area_label' => 'glasgow'),
            array('area_code' => '686', 'area_label' => 'glens falls'),
            array('area_code' => '430', 'area_label' => 'goa'),
            array('area_code' => '590', 'area_label' => 'gold coast'),
            array('area_code' => '373', 'area_label' => 'gold country'),
            array('area_code' => '538', 'area_label' => 'granada'),
            array('area_code' => '667', 'area_label' => 'grand forks'),
            array('area_code' => '432', 'area_label' => 'grand island'),
            array('area_code' => '129', 'area_label' => 'grand rapids'),
            array('area_code' => '660', 'area_label' => 'great falls'),
            array('area_code' => '144', 'area_label' => 'greece'),
            array('area_code' => '241', 'area_label' => 'green bay'),
            array('area_code' => '61', 'area_label' => 'greensboro'),
            array('area_code' => '253', 'area_label' => 'greenville/upstate'),
            array('area_code' => '525', 'area_label' => 'grenoble'),
            array('area_code' => '404', 'area_label' => 'guadalajara'),
            array('area_code' => '245', 'area_label' => 'guam-micronesia'),
            array('area_code' => '431', 'area_label' => 'guanajuato'),
            array('area_code' => '409', 'area_label' => 'guangzhou'),
            array('area_code' => '585', 'area_label' => 'guatemala'),
            array('area_code' => '482', 'area_label' => 'guelph'),
            array('area_code' => '230', 'area_label' => 'gulfport/biloxi'),
            array('area_code' => '391', 'area_label' => 'haifa'),
            array('area_code' => '174', 'area_label' => 'halifax'),
            array('area_code' => '140', 'area_label' => 'hamburg'),
            array('area_code' => '213', 'area_label' => 'hamilton-burlington'),
            array('area_code' => '403', 'area_label' => 'hampshire'),
            array('area_code' => '48', 'area_label' => 'hampton roads'),
            array('area_code' => '709', 'area_label' => 'hanford-corcoran'),
            array('area_code' => '500', 'area_label' => 'hangzhou'),
            array('area_code' => '417', 'area_label' => 'hannover'),
            array('area_code' => '166', 'area_label' => 'harrisburg'),
            array('area_code' => '447', 'area_label' => 'harrisonburg'),
            array('area_code' => '44', 'area_label' => 'hartford'),
            array('area_code' => '374', 'area_label' => 'hattiesburg'),
            array('area_code' => '28', 'area_label' => 'hawaii'),
            array('area_code' => '639', 'area_label' => 'heartland florida'),
            array('area_code' => '519', 'area_label' => 'heidelberg'),
            array('area_code' => '659', 'area_label' => 'helena'),
            array('area_code' => '506', 'area_label' => 'hermosillo'),
            array('area_code' => '462', 'area_label' => 'hickory/lenoir'),
            array('area_code' => '288', 'area_label' => 'high rockies'),
            array('area_code' => '353', 'area_label' => 'hilton head'),
            array('area_code' => '504', 'area_label' => 'hiroshima'),
            array('area_code' => '630', 'area_label' => 'holland'),
            array('area_code' => '87', 'area_label' => 'hong kong'),
            array('area_code' => '643', 'area_label' => 'houma'),
            array('area_code' => '23', 'area_label' => 'houston'),
            array('area_code' => '249', 'area_label' => 'hudson valley'),
            array('area_code' => '189', 'area_label' => 'humboldt county'),
            array('area_code' => '442', 'area_label' => 'huntington-ashland'),
            array('area_code' => '231', 'area_label' => 'huntsville/decatur'),
            array('area_code' => '183', 'area_label' => 'hyderabad'),
            array('area_code' => '605', 'area_label' => 'iloilo'),
            array('area_code' => '455', 'area_label' => 'imperial county'),
            array('area_code' => '45', 'area_label' => 'indianapolis'),
            array('area_code' => '157', 'area_label' => 'indonesia'),
            array('area_code' => '549', 'area_label' => 'indore'),
            array('area_code' => '104', 'area_label' => 'inland empire'),
            array('area_code' => '339', 'area_label' => 'iowa city'),
            array('area_code' => '589', 'area_label' => 'iran'),
            array('area_code' => '588', 'area_label' => 'iraq'),
            array('area_code' => '201', 'area_label' => 'ithaca'),
            array('area_code' => '426', 'area_label' => 'jackson, MI'),
            array('area_code' => '134', 'area_label' => 'jackson, MS'),
            array('area_code' => '558', 'area_label' => 'jackson, TN'),
            array('area_code' => '80', 'area_label' => 'jacksonville, FL'),
            array('area_code' => '634', 'area_label' => 'jacksonville, NC'),
            array('area_code' => '550', 'area_label' => 'jaipur'),
            array('area_code' => '553', 'area_label' => 'janesville'),
            array('area_code' => '561', 'area_label' => 'jersey shore'),
            array('area_code' => '161', 'area_label' => 'jerusalem'),
            array('area_code' => '185', 'area_label' => 'johannesburg'),
            array('area_code' => '425', 'area_label' => 'jonesboro'),
            array('area_code' => '423', 'area_label' => 'joplin'),
            array('area_code' => '618', 'area_label' => 'kaiserslautern'),
            array('area_code' => '261', 'area_label' => 'kalamazoo'),
            array('area_code' => '662', 'area_label' => 'kalispell'),
            array('area_code' => '381', 'area_label' => 'kamloops'),
            array('area_code' => '30', 'area_label' => 'kansas city, MO'),
            array('area_code' => '380', 'area_label' => 'kelowna/okanagan'),
            array('area_code' => '678', 'area_label' => 'kenai peninsula'),
            array('area_code' => '324', 'area_label' => 'kennewick-pasco-richland'),
            array('area_code' => '552', 'area_label' => 'kenosha-racine'),
            array('area_code' => '493', 'area_label' => 'kent'),
            array('area_code' => '582', 'area_label' => 'kenya'),
            array('area_code' => '410', 'area_label' => 'kerala'),
            array('area_code' => '327', 'area_label' => 'killeen/temple/ft hood'),
            array('area_code' => '385', 'area_label' => 'kingston, ON'),
            array('area_code' => '696', 'area_label' => 'kirksville'),
            array('area_code' => '214', 'area_label' => 'kitchener-waterloo-cambridge'),
            array('area_code' => '675', 'area_label' => 'klamath falls'),
            array('area_code' => '202', 'area_label' => 'knoxville'),
            array('area_code' => '672', 'area_label' => 'kokomo'),
            array('area_code' => '184', 'area_label' => 'kolkata (calcutta)'),
            array('area_code' => '474', 'area_label' => 'kootenays'),
            array('area_code' => '577', 'area_label' => 'kuwait'),
            array('area_code' => '363', 'area_label' => 'la crosse'),
            array('area_code' => '698', 'area_label' => 'la salle co'),
            array('area_code' => '283', 'area_label' => 'lafayette'),
            array('area_code' => '360', 'area_label' => 'lafayette/west lafayette'),
            array('area_code' => '284', 'area_label' => 'lake charles'),
            array('area_code' => '695', 'area_label' => 'lake of the ozarks'),
            array('area_code' => '376', 'area_label' => 'lakeland'),
            array('area_code' => '279', 'area_label' => 'lancaster, PA'),
            array('area_code' => '212', 'area_label' => 'lansing'),
            array('area_code' => '271', 'area_label' => 'laredo'),
            array('area_code' => '334', 'area_label' => 'las cruces'),
            array('area_code' => '26', 'area_label' => 'las vegas'),
            array('area_code' => '615', 'area_label' => 'lausanne'),
            array('area_code' => '347', 'area_label' => 'lawrence'),
            array('area_code' => '422', 'area_label' => 'lawton'),
            array('area_code' => '123', 'area_label' => 'leeds'),
            array('area_code' => '167', 'area_label' => 'lehigh valley'),
            array('area_code' => '520', 'area_label' => 'leipzig'),
            array('area_code' => '476', 'area_label' => 'lethbridge'),
            array('area_code' => '654', 'area_label' => 'lewiston/clarkston'),
            array('area_code' => '133', 'area_label' => 'lexington, KY'),
            array('area_code' => '413', 'area_label' => 'lille'),
            array('area_code' => '437', 'area_label' => 'lima/findlay'),
            array('area_code' => '282', 'area_label' => 'lincoln'),
            array('area_code' => '540', 'area_label' => 'lisbon'),
            array('area_code' => '100', 'area_label' => 'little rock'),
            array('area_code' => '118', 'area_label' => 'liverpool'),
            array('area_code' => '448', 'area_label' => 'logan'),
            array('area_code' => '415', 'area_label' => 'loire valley'),
            array('area_code' => '234', 'area_label' => 'london, ON'),
            array('area_code' => '24', 'area_label' => 'london, UK'),
            array('area_code' => '250', 'area_label' => 'long island'),
            array('area_code' => '7', 'area_label' => 'los angeles'),
            array('area_code' => '58', 'area_label' => 'louisville'),
            array('area_code' => '267', 'area_label' => 'lubbock'),
            array('area_code' => '611', 'area_label' => 'lucknow'),
            array('area_code' => '544', 'area_label' => 'luxembourg'),
            array('area_code' => '366', 'area_label' => 'lynchburg'),
            array('area_code' => '150', 'area_label' => 'lyon'),
            array('area_code' => '257', 'area_label' => 'macon/warner robins'),
            array('area_code' => '165', 'area_label' => 'madison'),
            array('area_code' => '110', 'area_label' => 'madrid'),
            array('area_code' => '169', 'area_label' => 'maine'),
            array('area_code' => '539', 'area_label' => 'malaga'),
            array('area_code' => '297', 'area_label' => 'malaysia'),
            array('area_code' => '71', 'area_label' => 'manchester'),
            array('area_code' => '428', 'area_label' => 'manhattan, KS'),
            array('area_code' => '90', 'area_label' => 'manila'),
            array('area_code' => '421', 'area_label' => 'mankato'),
            array('area_code' => '436', 'area_label' => 'mansfield'),
            array('area_code' => '149', 'area_label' => 'marseille'),
            array('area_code' => '692', 'area_label' => 'mason city'),
            array('area_code' => '699', 'area_label' => 'mattoon-charleston'),
            array('area_code' => '509', 'area_label' => 'mazatlan'),
            array('area_code' => '263', 'area_label' => 'mcallen/edinburg'),
            array('area_code' => '706', 'area_label' => 'meadville'),
            array('area_code' => '216', 'area_label' => 'medford-ashland'),
            array('area_code' => '619', 'area_label' => 'medicine hat'),
            array('area_code' => '65', 'area_label' => 'melbourne'),
            array('area_code' => '46', 'area_label' => 'memphis, TN'),
            array('area_code' => '454', 'area_label' => 'mendocino county'),
            array('area_code' => '285', 'area_label' => 'merced'),
            array('area_code' => '641', 'area_label' => 'meridian'),
            array('area_code' => '91', 'area_label' => 'mexico city'),
            array('area_code' => '111', 'area_label' => 'milan'),
            array('area_code' => '47', 'area_label' => 'milwaukee'),
            array('area_code' => '19', 'area_label' => 'minneapolis/st paul'),
            array('area_code' => '656', 'area_label' => 'missoula'),
            array('area_code' => '200', 'area_label' => 'mobile'),
            array('area_code' => '96', 'area_label' => 'modesto'),
            array('area_code' => '565', 'area_label' => 'mohave county'),
            array('area_code' => '563', 'area_label' => 'monroe, LA'),
            array('area_code' => '629', 'area_label' => 'monroe, MI'),
            array('area_code' => '102', 'area_label' => 'monterey bay'),
            array('area_code' => '408', 'area_label' => 'monterrey'),
            array('area_code' => '543', 'area_label' => 'montevideo'),
            array('area_code' => '207', 'area_label' => 'montgomery'),
            array('area_code' => '524', 'area_label' => 'montpellier'),
            array('area_code' => '49', 'area_label' => 'montreal'),
            array('area_code' => '440', 'area_label' => 'morgantown'),
            array('area_code' => '580', 'area_label' => 'morocco'),
            array('area_code' => '137', 'area_label' => 'moscow'),
            array('area_code' => '655', 'area_label' => 'moses lake'),
            array('area_code' => '85', 'area_label' => 'mumbai'),
            array('area_code' => '361', 'area_label' => 'muncie/anderson'),
            array('area_code' => '142', 'area_label' => 'munich'),
            array('area_code' => '554', 'area_label' => 'muskegon'),
            array('area_code' => '254', 'area_label' => 'myrtle beach'),
            array('area_code' => '501', 'area_label' => 'nagoya'),
            array('area_code' => '382', 'area_label' => 'nanaimo'),
            array('area_code' => '599', 'area_label' => 'nanjing'),
            array('area_code' => '151', 'area_label' => 'napoli/campania'),
            array('area_code' => '32', 'area_label' => 'nashville'),
            array('area_code' => '379', 'area_label' => 'new brunswick'),
            array('area_code' => '198', 'area_label' => 'new hampshire'),
            array('area_code' => '168', 'area_label' => 'new haven'),
            array('area_code' => '31', 'area_label' => 'new orleans'),
            array('area_code' => '291', 'area_label' => 'new river valley'),
            array('area_code' => '3', 'area_label' => 'new york city'),
            array('area_code' => '163', 'area_label' => 'newcastle/NE england'),
            array('area_code' => '591', 'area_label' => 'newcastle, NSW'),
            array('area_code' => '386', 'area_label' => 'niagara region'),
            array('area_code' => '586', 'area_label' => 'nicaragua'),
            array('area_code' => '306', 'area_label' => 'nice/cote d\'azur'),
            array('area_code' => '527', 'area_label' => 'normandy'),
            array('area_code' => '638', 'area_label' => 'north central FL'),
            array('area_code' => '196', 'area_label' => 'north dakota'),
            array('area_code' => '170', 'area_label' => 'north jersey'),
            array('area_code' => '375', 'area_label' => 'north mississippi'),
            array('area_code' => '668', 'area_label' => 'north platte'),
            array('area_code' => '682', 'area_label' => 'northeast SD'),
            array('area_code' => '309', 'area_label' => 'northern michigan'),
            array('area_code' => '443', 'area_label' => 'northern panhandle'),
            array('area_code' => '631', 'area_label' => 'northern WI'),
            array('area_code' => '354', 'area_label' => 'northwest CT'),
            array('area_code' => '636', 'area_label' => 'northwest GA'),
            array('area_code' => '688', 'area_label' => 'northwest KS'),
            array('area_code' => '650', 'area_label' => 'northwest OK'),
            array('area_code' => '105', 'area_label' => 'norway'),
            array('area_code' => '492', 'area_label' => 'nottingham'),
            array('area_code' => '614', 'area_label' => 'nuremberg'),
            array('area_code' => '510', 'area_label' => 'oaxaca'),
            array('area_code' => '333', 'area_label' => 'ocala'),
            array('area_code' => '268', 'area_label' => 'odessa/midland'),
            array('area_code' => '351', 'area_label' => 'ogden-clearfield'),
            array('area_code' => '640', 'area_label' => 'okaloosa/walton'),
            array('area_code' => '429', 'area_label' => 'okinawa'),
            array('area_code' => '54', 'area_label' => 'oklahoma city'),
            array('area_code' => '466', 'area_label' => 'olympic peninsula'),
            array('area_code' => '55', 'area_label' => 'omaha/council bluffs'),
            array('area_code' => '684', 'area_label' => 'oneonta'),
            array('area_code' => '103', 'area_label' => 'orange county'),
            array('area_code' => '321', 'area_label' => 'oregon coast'),
            array('area_code' => '39', 'area_label' => 'orlando'),
            array('area_code' => '120', 'area_label' => 'osaka-kobe-kyoto'),
            array('area_code' => '76', 'area_label' => 'ottawa-hull-gatineau'),
            array('area_code' => '336', 'area_label' => 'outer banks'),
            array('area_code' => '487', 'area_label' => 'owen sound'),
            array('area_code' => '673', 'area_label' => 'owensboro'),
            array('area_code' => '211', 'area_label' => 'oxford'),
            array('area_code' => '294', 'area_label' => 'pakistan'),
            array('area_code' => '209', 'area_label' => 'palm springs, CA'),
            array('area_code' => '608', 'area_label' => 'pampanga'),
            array('area_code' => '298', 'area_label' => 'panama'),
            array('area_code' => '562', 'area_label' => 'panama city, FL'),
            array('area_code' => '81', 'area_label' => 'paris'),
            array('area_code' => '441', 'area_label' => 'parkersburg-marietta'),
            array('area_code' => '620', 'area_label' => 'peace river country'),
            array('area_code' => '203', 'area_label' => 'pensacola'),
            array('area_code' => '224', 'area_label' => 'peoria'),
            array('area_code' => '67', 'area_label' => 'perth'),
            array('area_code' => '159', 'area_label' => 'peru'),
            array('area_code' => '530', 'area_label' => 'perugia'),
            array('area_code' => '388', 'area_label' => 'peterborough'),
            array('area_code' => '17', 'area_label' => 'philadelphia'),
            array('area_code' => '18', 'area_label' => 'phoenix'),
            array('area_code' => '681', 'area_label' => 'pierre/central SD'),
            array('area_code' => '33', 'area_label' => 'pittsburgh'),
            array('area_code' => '338', 'area_label' => 'plattsburgh-adirondacks'),
            array('area_code' => '356', 'area_label' => 'poconos'),
            array('area_code' => '147', 'area_label' => 'poland'),
            array('area_code' => '555', 'area_label' => 'port huron'),
            array('area_code' => '9', 'area_label' => 'portland, OR'),
            array('area_code' => '541', 'area_label' => 'porto'),
            array('area_code' => '515', 'area_label' => 'porto alegre'),
            array('area_code' => '683', 'area_label' => 'potsdam-canton-massena'),
            array('area_code' => '138', 'area_label' => 'prague'),
            array('area_code' => '419', 'area_label' => 'prescott'),
            array('area_code' => '595', 'area_label' => 'pretoria'),
            array('area_code' => '304', 'area_label' => 'prince edward island'),
            array('area_code' => '383', 'area_label' => 'prince george'),
            array('area_code' => '292', 'area_label' => 'provo/orem'),
            array('area_code' => '508', 'area_label' => 'puebla'),
            array('area_code' => '315', 'area_label' => 'pueblo'),
            array('area_code' => '180', 'area_label' => 'puerto rico'),
            array('area_code' => '407', 'area_label' => 'puerto vallarta'),
            array('area_code' => '368', 'area_label' => 'pullman/moscow'),
            array('area_code' => '317', 'area_label' => 'pune'),
            array('area_code' => '307', 'area_label' => 'quad cities, IA/IL'),
            array('area_code' => '175', 'area_label' => 'quebec city'),
            array('area_code' => '36', 'area_label' => 'raleigh/durham/CH'),
            array('area_code' => '680', 'area_label' => 'rapid city/west SD'),
            array('area_code' => '278', 'area_label' => 'reading'),
            array('area_code' => '516', 'area_label' => 'recife'),
            array('area_code' => '475', 'area_label' => 'red deer'),
            array('area_code' => '188', 'area_label' => 'redding'),
            array('area_code' => '478', 'area_label' => 'regina'),
            array('area_code' => '92', 'area_label' => 'reno/tahoe'),
            array('area_code' => '579', 'area_label' => 'reykjavik'),
            array('area_code' => '38', 'area_label' => 'rhode island'),
            array('area_code' => '671', 'area_label' => 'richmond, IN'),
            array('area_code' => '60', 'area_label' => 'richmond, VA'),
            array('area_code' => '139', 'area_label' => 'rio de janeiro'),
            array('area_code' => '289', 'area_label' => 'roanoke'),
            array('area_code' => '316', 'area_label' => 'rochester, MN'),
            array('area_code' => '126', 'area_label' => 'rochester, NY'),
            array('area_code' => '223', 'area_label' => 'rockford'),
            array('area_code' => '574', 'area_label' => 'romania'),
            array('area_code' => '121', 'area_label' => 'rome'),
            array('area_code' => '459', 'area_label' => 'roseburg'),
            array('area_code' => '420', 'area_label' => 'roswell/carlsbad'),
            array('area_code' => '12', 'area_label' => 'sacramento'),
            array('area_code' => '260', 'area_label' => 'saginaw-midland-baycity'),
            array('area_code' => '480', 'area_label' => 'saguenay'),
            array('area_code' => '232', 'area_label' => 'salem, OR'),
            array('area_code' => '690', 'area_label' => 'salina'),
            array('area_code' => '56', 'area_label' => 'salt lake city'),
            array('area_code' => '392', 'area_label' => 'salvador, bahia'),
            array('area_code' => '646', 'area_label' => 'san angelo'),
            array('area_code' => '53', 'area_label' => 'san antonio'),
            array('area_code' => '8', 'area_label' => 'san diego'),
            array('area_code' => '191', 'area_label' => 'san luis obispo'),
            array('area_code' => '449', 'area_label' => 'san marcos'),
            array('area_code' => '573', 'area_label' => 'sandusky'),
            array('area_code' => '62', 'area_label' => 'santa barbara'),
            array('area_code' => '218', 'area_label' => 'santa fe/taos'),
            array('area_code' => '710', 'area_label' => 'santa maria'),
            array('area_code' => '113', 'area_label' => 'sao paulo'),
            array('area_code' => '502', 'area_label' => 'sapporo'),
            array('area_code' => '237', 'area_label' => 'sarasota-bradenton'),
            array('area_code' => '532', 'area_label' => 'sardinia'),
            array('area_code' => '486', 'area_label' => 'sarnia'),
            array('area_code' => '176', 'area_label' => 'saskatoon'),
            array('area_code' => '485', 'area_label' => 'sault ste marie, ON'),
            array('area_code' => '205', 'area_label' => 'savannah/hinesville'),
            array('area_code' => '669', 'area_label' => 'scottsbluff/panhandle'),
            array('area_code' => '276', 'area_label' => 'scranton/wilkes-barre'),
            array('area_code' => '2', 'area_label' => 'seattle-tacoma'),
            array('area_code' => '596', 'area_label' => 'sendai'),
            array('area_code' => '119', 'area_label' => 'seoul'),
            array('area_code' => '395', 'area_label' => 'sevilla'),
            array('area_code' => '1', 'area_label' => 'SF bay area'),
            array('area_code' => '135', 'area_label' => 'shanghai'),
            array('area_code' => '571', 'area_label' => 'sheboygan, WI'),
            array('area_code' => '401', 'area_label' => 'sheffield'),
            array('area_code' => '598', 'area_label' => 'shenyang'),
            array('area_code' => '499', 'area_label' => 'shenzhen'),
            array('area_code' => '390', 'area_label' => 'sherbrooke'),
            array('area_code' => '651', 'area_label' => 'show low'),
            array('area_code' => '206', 'area_label' => 'shreveport'),
            array('area_code' => '311', 'area_label' => 'sicilia'),
            array('area_code' => '468', 'area_label' => 'sierra vista'),
            array('area_code' => '89', 'area_label' => 'singapore'),
            array('area_code' => '341', 'area_label' => 'sioux city, IA'),
            array('area_code' => '679', 'area_label' => 'sioux falls/SE SD'),
            array('area_code' => '708', 'area_label' => 'siskiyou county'),
            array('area_code' => '461', 'area_label' => 'skagit/island/SJI'),
            array('area_code' => '623', 'area_label' => 'skeena-bulkley'),
            array('area_code' => '228', 'area_label' => 'south bend/michiana'),
            array('area_code' => '378', 'area_label' => 'south coast'),
            array('area_code' => '195', 'area_label' => 'south dakota'),
            array('area_code' => '20', 'area_label' => 'south florida'),
            array('area_code' => '286', 'area_label' => 'south jersey'),
            array('area_code' => '676', 'area_label' => 'southeast alaska'),
            array('area_code' => '691', 'area_label' => 'southeast IA'),
            array('area_code' => '689', 'area_label' => 'southeast KS'),
            array('area_code' => '566', 'area_label' => 'southeast missouri'),
            array('area_code' => '345', 'area_label' => 'southern illinois'),
            array('area_code' => '556', 'area_label' => 'southern maryland'),
            array('area_code' => '632', 'area_label' => 'southern WV'),
            array('area_code' => '687', 'area_label' => 'southwest KS'),
            array('area_code' => '572', 'area_label' => 'southwest michigan'),
            array('area_code' => '665', 'area_label' => 'southwest MN'),
            array('area_code' => '642', 'area_label' => 'southwest MS'),
            array('area_code' => '648', 'area_label' => 'southwest TX'),
            array('area_code' => '712', 'area_label' => 'southwest VA'),
            array('area_code' => '331', 'area_label' => 'space coast'),
            array('area_code' => '95', 'area_label' => 'spokane/coeur d\'alene'),
            array('area_code' => '225', 'area_label' => 'springfield, IL'),
            array('area_code' => '221', 'area_label' => 'springfield, MO'),
            array('area_code' => '557', 'area_label' => 'st augustine'),
            array('area_code' => '369', 'area_label' => 'st cloud'),
            array('area_code' => '352', 'area_label' => 'st george'),
            array('area_code' => '305', 'area_label' => 'st john\'s, NL'),
            array('area_code' => '694', 'area_label' => 'st joseph'),
            array('area_code' => '29', 'area_label' => 'st louis, MO'),
            array('area_code' => '143', 'area_label' => 'st petersburg, RU'),
            array('area_code' => '277', 'area_label' => 'state college'),
            array('area_code' => '635', 'area_label' => 'statesboro'),
            array('area_code' => '433', 'area_label' => 'stillwater'),
            array('area_code' => '97', 'area_label' => 'stockton'),
            array('area_code' => '414', 'area_label' => 'strasbourg'),
            array('area_code' => '416', 'area_label' => 'stuttgart'),
            array('area_code' => '384', 'area_label' => 'sudbury'),
            array('area_code' => '622', 'area_label' => 'sunshine coast'),
            array('area_code' => '613', 'area_label' => 'surat surat'),
            array('area_code' => '707', 'area_label' => 'susanville'),
            array('area_code' => '106', 'area_label' => 'sweden'),
            array('area_code' => '64', 'area_label' => 'sydney'),
            array('area_code' => '130', 'area_label' => 'syracuse'),
            array('area_code' => '155', 'area_label' => 'taiwan'),
            array('area_code' => '186', 'area_label' => 'tallahassee'),
            array('area_code' => '37', 'area_label' => 'tampa bay area'),
            array('area_code' => '490', 'area_label' => 'tasmania'),
            array('area_code' => '160', 'area_label' => 'tel aviv'),
            array('area_code' => '348', 'area_label' => 'terre haute'),
            array('area_code' => '488', 'area_label' => 'territories'),
            array('area_code' => '359', 'area_label' => 'texarkana'),
            array('area_code' => '649', 'area_label' => 'texoma'),
            array('area_code' => '156', 'area_label' => 'thailand'),
            array('area_code' => '627', 'area_label' => 'the thumb'),
            array('area_code' => '387', 'area_label' => 'thunder bay'),
            array('area_code' => '181', 'area_label' => 'tijuana'),
            array('area_code' => '88', 'area_label' => 'tokyo'),
            array('area_code' => '204', 'area_label' => 'toledo'),
            array('area_code' => '280', 'area_label' => 'topeka'),
            array('area_code' => '397', 'area_label' => 'torino'),
            array('area_code' => '25', 'area_label' => 'toronto'),
            array('area_code' => '411', 'area_label' => 'toulouse'),
            array('area_code' => '332', 'area_label' => 'treasure coast'),
            array('area_code' => '323', 'area_label' => 'tri-cities, TN'),
            array('area_code' => '479', 'area_label' => 'trois-rivieres'),
            array('area_code' => '57', 'area_label' => 'tucson'),
            array('area_code' => '70', 'area_label' => 'tulsa'),
            array('area_code' => '581', 'area_label' => 'tunisia'),
            array('area_code' => '148', 'area_label' => 'turkey'),
            array('area_code' => '371', 'area_label' => 'tuscaloosa'),
            array('area_code' => '703', 'area_label' => 'tuscarawas co'),
            array('area_code' => '469', 'area_label' => 'twin falls'),
            array('area_code' => '704', 'area_label' => 'twin tiers NY/PA'),
            array('area_code' => '308', 'area_label' => 'tyler/east TX'),
            array('area_code' => '583', 'area_label' => 'ukraine'),
            array('area_code' => '215', 'area_label' => 'united arab emirates'),
            array('area_code' => '262', 'area_label' => 'upper peninsula'),
            array('area_code' => '247', 'area_label' => 'utica-rome-oneida'),
            array('area_code' => '427', 'area_label' => 'valdosta'),
            array('area_code' => '394', 'area_label' => 'valencia'),
            array('area_code' => '16', 'area_label' => 'vancouver, BC'),
            array('area_code' => '178', 'area_label' => 'venezuela'),
            array('area_code' => '310', 'area_label' => 'venice/veneto'),
            array('area_code' => '208', 'area_label' => 'ventura county'),
            array('area_code' => '507', 'area_label' => 'veracruz'),
            array('area_code' => '93', 'area_label' => 'vermont'),
            array('area_code' => '177', 'area_label' => 'victoria, BC'),
            array('area_code' => '564', 'area_label' => 'victoria, TX'),
            array('area_code' => '122', 'area_label' => 'vienna'),
            array('area_code' => '314', 'area_label' => 'vietnam'),
            array('area_code' => '616', 'area_label' => 'virgin islands'),
            array('area_code' => '346', 'area_label' => 'visalia-tulare'),
            array('area_code' => '270', 'area_label' => 'waco'),
            array('area_code' => '10', 'area_label' => 'washington, DC'),
            array('area_code' => '567', 'area_label' => 'waterloo/cedar falls'),
            array('area_code' => '337', 'area_label' => 'watertown'),
            array('area_code' => '458', 'area_label' => 'wausau'),
            array('area_code' => '302', 'area_label' => 'wellington'),
            array('area_code' => '325', 'area_label' => 'wenatchee'),
            array('area_code' => '551', 'area_label' => 'west bank'),
            array('area_code' => '194', 'area_label' => 'west virginia (old)'),
            array('area_code' => '697', 'area_label' => 'western IL'),
            array('area_code' => '377', 'area_label' => 'western KY'),
            array('area_code' => '329', 'area_label' => 'western maryland'),
            array('area_code' => '173', 'area_label' => 'western massachusetts'),
            array('area_code' => '320', 'area_label' => 'western slope'),
            array('area_code' => '472', 'area_label' => 'whistler, BC'),
            array('area_code' => '625', 'area_label' => 'whitehorse'),
            array('area_code' => '99', 'area_label' => 'wichita'),
            array('area_code' => '365', 'area_label' => 'wichita falls'),
            array('area_code' => '463', 'area_label' => 'williamsport'),
            array('area_code' => '274', 'area_label' => 'wilmington, NC'),
            array('area_code' => '711', 'area_label' => 'winchester'),
            array('area_code' => '235', 'area_label' => 'windsor'),
            array('area_code' => '79', 'area_label' => 'winnipeg'),
            array('area_code' => '272', 'area_label' => 'winston-salem'),
            array('area_code' => '593', 'area_label' => 'wollongong'),
            array('area_code' => '240', 'area_label' => 'worcester/central MA'),
            array('area_code' => '597', 'area_label' => 'wuhan'),
            array('area_code' => '197', 'area_label' => 'wyoming'),
            array('area_code' => '603', 'area_label' => 'xi\'an'),
            array('area_code' => '246', 'area_label' => 'yakima'),
            array('area_code' => '624', 'area_label' => 'yellowknife'),
            array('area_code' => '357', 'area_label' => 'york, PA'),
            array('area_code' => '252', 'area_label' => 'youngstown'),
            array('area_code' => '456', 'area_label' => 'yuba-sutter'),
            array('area_code' => '405', 'area_label' => 'yucatan'),
            array('area_code' => '370', 'area_label' => 'yuma'),
            array('area_code' => '607', 'area_label' => 'zamboanga'),
            array('area_code' => '702', 'area_label' => 'zanesville/cambridge'),
            array('area_code' => '112', 'area_label' => 'zurich'),
        );
    }

    public static function getSubareas() {
        return array(
            array('id' => '18-1', 'subarea' => 'Phoenix - Central-South Phx - AZ', 'default' => true),
            array('id' => '18-2', 'subarea' => 'Phoenix - East Valley - AZ', 'default' => true),
            array('id' => '18-3', 'subarea' => 'Phoenix - Phx North - AZ', 'default' => true),
            array('id' => '18-4', 'subarea' => 'West Valley - AZ', 'default' => true),
            // array('id' => '16-1', 'subarea' => 'Vancouver - Vancouver'),
            // array('id' => '16-2', 'subarea' => 'Vancouver - North Shore'),
            // array('id' => '16-3', 'subarea' => 'Vancouver - Burnaby-Newwest'),
            // array('id' => '16-4', 'subarea' => 'Vancouver - Delta-Surrey-Langley'),
            // array('id' => '16-5', 'subarea' => 'Vancouver - Tricities-Pitt-Maple'),
            // array('id' => '16-6', 'subarea' => 'Vancouver - Richmond'),
//                    array('id' => '1', 'subarea' => 'San Diego - City of San Diego - CA', 'default' => true),
            array('id' => '8-1', 'subarea' => 'San Diego - City of San Diego - CA', 'default' => true),
            array('id' => '8-2', 'subarea' => 'San Diego - North San Diego County - CA', 'default' => true),
            array('id' => '8-3', 'subarea' => 'San Diego - East San Diego County - CA', 'default' => true),
            array('id' => '8-4', 'subarea' => 'San Diego - South San Diego County - CA', 'default' => true),
            array('id' => '7-1', 'subarea' => 'Los Angeles - Westside-Southbay-310 - CA'),
            array('id' => '7-2', 'subarea' => 'Los Angeles - San Fernando Valley - CA', 'default' => true),
            array('id' => '7-3', 'subarea' => 'Los Angeles - Central LA 213-323 - CA', 'default' => true),
            array('id' => '7-4', 'subarea' => 'Los Angeles - San Gabriel Valley - CA', 'default' => true),
            array('id' => '7-5', 'subarea' => 'Los Angeles - Long beach-562 - CA', 'default' => true),
            array('id' => '7-6', 'subarea' => 'Los Angeles - Antelope Valley - CA', 'default' => true),
            array('id' => '104', 'subarea' => 'Inland Empire - CA', 'default' => true),
            array('id' => '103', 'subarea' => 'Orange County - CA', 'default' => true),
            array('id' => '12', 'subarea' => 'Sacramento - CA', 'default' => true),
            array('id' => '13', 'subarea' => 'Denver - CO', 'default' => true),
            // array('id' => '', 'subarea' => 'Fairfield County - CT', 'default' => true),
            array('id' => '10-1', 'subarea' => 'Washington - District of Columbia - DC'),
            array('id' => '10-2', 'subarea' => 'Washington - Northern Virginia - DC'),
            array('id' => '10-3', 'subarea' => 'Washington - Maryland - DC'),
            //array('id' => '', 'subarea' => 'Fort Lauderdale - Miami/Dade County -FL', 'default' => true),
            // array('id' => '', 'subarea' => 'Fort Lauderdale - Broward County - FL', 'default' => true),
            //array('id' => '', 'subarea' => 'Fort Lauderdale - Palm Beach County - FL', 'default' => true),
            array('id' => '125-1', 'subarea' => 'Ft Myers-SW Florida - Lee County - FL'),
            array('id' => '125-2', 'subarea' => 'Ft Myers-SW Florida - Charlotte County - FL'),
            array('id' => '125-3', 'subarea' => 'Ft Myers-SW Florida - Collier County - FL'),
            array('id' => '37-1', 'subarea' => 'Tampa Bay Area - Hernando Co - FL'),
            array('id' => '37-2', 'subarea' => 'Tampa Bay Area - Hillsborough Co - FL'),
            array('id' => '37-3', 'subarea' => 'Tampa Bay Area - Pasco Co - FL'),
            array('id' => '37-4', 'subarea' => 'Tampa Bay Area - Pinellas Co - FL'),
            array('id' => '80', 'subarea' => 'Jacksonville - FL'),
            array('id' => '39', 'subarea' => 'Orlando - FL'),
            // array('id' => '', 'subarea' => 'West Palm Beach - Miami/Dade County - FL', 'default' => true),
            //array('id' => '', 'subarea' => 'West Palm Beach - Broward County - FL', 'default' => true),
            //array('id' => '', 'subarea' => 'West Palm Beach - Palm Beach County - FL', 'default' => true),
            array('id' => '14-1', 'subarea' => 'Atlanta - City of Atlanta - GA', 'default' => true),
            array('id' => '14-2', 'subarea' => 'Atlanta - Otp North - GA', 'default' => true),
            array('id' => '14-3', 'subarea' => 'Atlanta - Otp East - GA', 'default' => true),
            array('id' => '14-4', 'subarea' => 'Atlanta - Otp South - GA', 'default' => true),
            array('id' => '14-5', 'subarea' => 'Atlanta - Otp West - GA', 'default' => true),
            array('id' => '28-1', 'subarea' => 'Hawaii - Honolulu - Oahu - HI'),
            array('id' => '28-2', 'subarea' => 'Hawaii - Big Island - HI'),
            array('id' => '28-3', 'subarea' => 'Hawaii - Maui - HI'),
            array('id' => '28-4', 'subarea' => 'Hawaii - Kauai - HI'),
            array('id' => '28-5', 'subarea' => 'Hawaii - Molokai - HI'),
            array('id' => '11-1', 'subarea' => 'Chicago - City of Chicago - IL', 'default' => true),
            array('id' => '11-2', 'subarea' => 'Chicago - North Chicagoland - IL', 'default' => true),
            array('id' => '11-3', 'subarea' => 'Chicago - West Chicagoland- IL', 'default' => true),
            array('id' => '11-4', 'subarea' => 'Chicago - South Chicagoland - IL', 'default' => true),
            array('id' => '11-5', 'subarea' => 'Chicago - Northwest Indiana - IL', 'default' => true),
            array('id' => '11-6', 'subarea' => 'Chicago - Northwest Suburbs - IL', 'default' => true),
            array('id' => '45', 'subarea' => 'Indianapolis - IN', 'default' => true),
            array('id' => '34', 'subarea' => 'Baltimore - MD'),
            array('id' => '4-1', 'subarea' => 'Boston - Boston-Cambridge-Brookline - MA'),
            array('id' => '4-2', 'subarea' => 'Boston - Northwest-Merrimack - MA'),
            array('id' => '4-3', 'subarea' => 'Boston - Metro West - MA'),
            array('id' => '4-4', 'subarea' => 'Boston - North Shore - MA'),
            array('id' => '4-5', 'subarea' => 'Boston - South Shore - MA'),
            array('id' => '22-1', 'subarea' => 'Detroit Metro - Macomb County - MI', 'default' => true),
            array('id' => '22-2', 'subarea' => 'Detroit Metro - Wayne County - MI', 'default' => true),
            array('id' => '22-3', 'subarea' => 'Detroit Metro - Oakland County - MI', 'default' => true),
            array('id' => '19-1', 'subarea' => 'Minneapolis-St. Paul - Hennepin County - MN', 'default' => true),
            array('id' => '19-2', 'subarea' => 'Minneapolis-St. Paul - Ramsey County - MN', 'default' => true),
            array('id' => '19-3', 'subarea' => 'Minneapolis-St. Paul - Anoka-Chisago-Isanti - MN', 'default' => true),
            array('id' => '19-4', 'subarea' => 'Minneapolis-St. Paul - Washington Co-WI - MN', 'default' => true),
            array('id' => '19-5', 'subarea' => 'Minneapolis-St. Paul - Dakota-Scott - MN', 'default' => true),
            array('id' => '19-6', 'subarea' => 'Minneapolis-St. Paul - Carver-Sherburne-Wright - MN', 'default' => true),
            array('id' => '30', 'subarea' => 'Kansas City - MO', 'default' => true),
            array('id' => '29', 'subarea' => 'St Louis - MO', 'default' => true),
            array('id' => '26', 'subarea' => 'Las Vegas - NV', 'default' => true),
            array('id' => '198', 'subarea' => 'New Hampshire - NH'),
            array('id' => '349', 'subarea' => 'Central NJ - NJ'),
            array('id' => '170', 'subarea' => 'North Jersey - NJ'),
            array('id' => '286', 'subarea' => 'South Jersey - NJ'),
            array('id' => '250', 'subarea' => 'Long Island - NY', 'default' => true),
            array('id' => '3-1', 'subarea' => 'New York City - Manhattan - NY'),
            array('id' => '3-2', 'subarea' => 'New York City - Brooklyn - NY', 'default' => true),
            array('id' => '3-3', 'subarea' => 'New York City - Queens - NY', 'default' => true),
            array('id' => '3-4', 'subarea' => 'New York City - Bronx - NY', 'default' => true),
            array('id' => '3-5', 'subarea' => 'New York City - Staten Island - NY', 'default' => true),
            array('id' => '3-6', 'subarea' => 'New York City - New Jersey - NY', 'default' => true),
            array('id' => '3-7', 'subarea' => 'New York City - Long Island - NY', 'default' => true),
            array('id' => '3-8', 'subarea' => 'New York City - Westchester - NY', 'default' => true),
            array('id' => '3-9', 'subarea' => 'New York City - Fairfield Co - CT - NY', 'default' => true),
            array('id' => '41', 'subarea' => 'Charlotte - NC', 'default' => true),
            array('id' => '36', 'subarea' => 'Raleigh-Durham-CH - NC', 'default' => true),
            array('id' => '35', 'subarea' => 'Cincinnati - OH', 'default' => true),
            array('id' => '27', 'subarea' => 'Cleveland - OH', 'default' => true),
            array('id' => '42', 'subarea' => 'Columbus - OH', 'default' => true),
            array('id' => '54', 'subarea' => 'Oklahoma City - OK', 'default' => true),
            array('id' => '70', 'subarea' => 'Tulsa - OK', 'default' => true),
            array('id' => '9-1', 'subarea' => 'Portland - Multnomah County - OR', 'default' => true),
            array('id' => '9-2', 'subarea' => 'Portland - Washington County - OR', 'default' => true),
            array('id' => '9-3', 'subarea' => 'Portland - Clark-Cowlitz WA - OR', 'default' => true),
            array('id' => '9-4', 'subarea' => 'Portland - Clackamas County - OR', 'default' => true),
            array('id' => '9-5', 'subarea' => 'Portland - North Coast - OR', 'default' => true),
            array('id' => '9-6', 'subarea' => 'Portland - Yamhill Co - OR', 'default' => true),
            array('id' => '9-7', 'subarea' => 'Portland - Columbia Gorge - OR', 'default' => true),
            array('id' => '17', 'subarea' => 'Philadelphia - PA', 'default' => true),
            array('id' => '33', 'subarea' => 'Pittsburgh - PA', 'default' => true),
            array('id' => '32', 'subarea' => 'Nashville - TN', 'default' => true),
            array('id' => '48', 'subarea' => 'Hampton Roads - VA', 'default' => true),
            array('id' => '60', 'subarea' => 'Richmond - VA', 'default' => true),
            array('id' => '2-1', 'subarea' => 'Seattle-tacoma - Seattle - WA', 'default' => true),
            array('id' => '2-2', 'subarea' => 'Seattle-tacoma - Eastside - WA', 'default' => true),
            array('id' => '2-3', 'subarea' => 'Seattle-tacoma - Snohomish County - WA', 'default' => true),
            array('id' => '2-4', 'subarea' => 'Seattle-tacoma - Kitsap-West Puget - WA', 'default' => true),
            array('id' => '2-5', 'subarea' => 'Seattle-tacoma - Tacoma-Pierce - WA', 'default' => true),
            array('id' => '2-6', 'subarea' => 'Seattle-tacoma - Olympia-Thurston - WA', 'default' => true),
            array('id' => '2-7', 'subarea' => 'Seattle-tacoma - South King Co - WA', 'default' => true),
            array('id' => '47', 'subarea' => 'Milwaukee - WI', 'default' => true),
            array('id' => '21-1', 'subarea' => 'Dallas-Fort Worth - Dallas - TX', 'default' => true),
            array('id' => '21-2', 'subarea' => 'Dallas-Fort Worth - Fort Worth - TX', 'default' => true),
            array('id' => '21-3', 'subarea' => 'Dallas-Fort Worth - Mid Cities - TX', 'default' => true),
            array('id' => '21-4', 'subarea' => 'Dallas-Fort Worth - North DFW - TX', 'default' => true),
            array('id' => '21-5', 'subarea' => 'Dallas-Fort Worth - South DFW - TX', 'default' => true),
            array('id' => '23', 'subarea' => 'Houston - TX', 'default' => true),
            array('id' => '53', 'subarea' => 'San Antonio - TX', 'default' => true),
            array('id' => '15', 'subarea' => 'Austin - TX', 'default' => true),
            array('id' => '20-1', 'subarea' => 'South Florida - miami - dade county - FL'),
            array('id' => '20-2', 'subarea' => 'South Florida - broward county - FL'),
            array('id' => '20-3', 'subarea' => 'South Florida - palm beach county - FL'),
            array('id' => '1-1', 'subarea' => 'SF bay area - city of san francisco - CA'),
            array('id' => '1-2', 'subarea' => 'SF bay area - south bay area - CA'),
            array('id' => '1-3', 'subarea' => 'SF bay area - east bay area - CA', 'default' => true),
            array('id' => '1-4', 'subarea' => 'SF bay area - peninsula - CA'),
            array('id' => '1-5', 'subarea' => 'SF bay area - north bay - marin - CA'),
            array('id' => '1-6', 'subarea' => 'SF bay area - santa cruz - CA'),
            array('id' => '127', 'subarea' => 'Birmingham - AL', 'default' => true),
            array('id' => '231', 'subarea' => 'huntsville - decatur - AL', 'default' => true),
            array('id' => '200', 'subarea' => 'Mobile - AL', 'default' => true),
            array('id' => '57', 'subarea' => 'Tucson - AZ', 'default' => true),
            array('id' => '293', 'subarea' => 'Fayetteville - AR', 'default' => true),
            array('id' => '100', 'subarea' => 'Little Rock - AR', 'default' => true),
            array('id' => '63', 'subarea' => 'Bakersfield - CA', 'default' => true),
            array('id' => '43', 'subarea' => 'fresno - madera - CA', 'default' => true),
            array('id' => '96', 'subarea' => 'Modesto - CA', 'default' => true),
            array('id' => '97', 'subarea' => 'Stockton - CA', 'default' => true),
            array('id' => '208', 'subarea' => 'Ventura County - CA', 'default' => true),
            array('id' => '210', 'subarea' => 'Colorado Springs - CO', 'default' => true),
            array('id' => '287', 'subarea' => 'Fort collins-north - CO', 'default' => true),
            array('id' => '44', 'subarea' => 'Hartford - CT'),
            array('id' => '168', 'subarea' => 'New haven - CT'),
            array('id' => '193', 'subarea' => 'Delaware - DE'),
            array('id' => '205', 'subarea' => 'savannah - hinesville - GA', 'default' => true),
            array('id' => '52', 'subarea' => 'Boise - ID', 'default' => true),
            array('id' => '223', 'subarea' => 'Rockford - IL', 'default' => true),
            array('id' => '226', 'subarea' => 'Fort wayne - IN'),
            array('id' => '228', 'subarea' => 'South bend-michiana - IN', 'default' => true),
            array('id' => '98', 'subarea' => 'Des Moines - IA', 'default' => true),
            array('id' => '99', 'subarea' => 'Wichita - KS', 'default' => true),
            array('id' => '133', 'subarea' => 'Lexington - KY'),
            array('id' => '58', 'subarea' => 'Louisville - KY', 'default' => true),
            array('id' => '240', 'subarea' => 'Worcester-central - MA', 'default' => true),
            array('id' => '172', 'subarea' => 'Ann arbor - MI', 'default' => true),
            array('id' => '212', 'subarea' => 'Lansing - MI', 'default' => true),
            array('id' => '282', 'subarea' => 'Lincoln - NE', 'default' => true),
            array('id' => '55', 'subarea' => 'Omaha-council bluffs - NE', 'default' => true),
            array('id' => '92', 'subarea' => 'Reno-tahoe - NV', 'default' => true),
            array('id' => '50', 'subarea' => 'Albuquerque - NM', 'default' => true),
            array('id' => '59', 'subarea' => 'Albany - NY', 'default' => true),
            array('id' => '40', 'subarea' => 'Buffalo - NY', 'default' => true),
            array('id' => '126', 'subarea' => 'Rochester - NY'),
            array('id' => '130', 'subarea' => 'Syracuse -  NY', 'default' => true),
            array('id' => '171', 'subarea' => 'Asheville - NC', 'default' => true),
            array('id' => '273', 'subarea' => 'Fayetteville - NC', 'default' => true),
            array('id' => '61', 'subarea' => 'Greensboro - NC', 'default' => true),
            array('id' => '274', 'subarea' => 'Wilmington - NC', 'default' => true),
            array('id' => '272', 'subarea' => 'Winston-salem - NC', 'default' => true),
            array('id' => '251', 'subarea' => 'Akron-canton - OH', 'default' => true),
            array('id' => '204', 'subarea' => 'Toledo - OH', 'default' => true),
            array('id' => '94', 'subarea' => 'Eugene - OR', 'default' => true),
            array('id' => '232', 'subarea' => 'Salem - OR', 'default' => true),
            array('id' => '166', 'subarea' => 'Harrisburg - PA', 'default' => true),
            array('id' => '279', 'subarea' => 'Lancaster - PA', 'default' => true),
            array('id' => '278', 'subarea' => 'Reading - PA', 'default' => true),
            array('id' => '276', 'subarea' => 'Scranton-wilkes-barre - PA', 'default' => true),
            array('id' => '357', 'subarea' => 'York - PA', 'default' => true),
            array('id' => '128', 'subarea' => 'Charleston - SC', 'default' => true),
            array('id' => '101', 'subarea' => 'Columbia - SC', 'default' => true),
            array('id' => '253', 'subarea' => 'Greenville-upstate - SC', 'default' => true),
            array('id' => '220', 'subarea' => 'Chattanooga - TN', 'default' => true),
            array('id' => '202', 'subarea' => 'Knoxville - TN', 'default' => true),
            array('id' => '46', 'subarea' => 'Memphis - TN', 'default' => true),
            array('id' => '132', 'subarea' => 'El paso - TX', 'default' => true),
            array('id' => '263', 'subarea' => 'Mcallen - edinburg - TX'),
            array('id' => '308', 'subarea' => 'Tyler-east - TX'),
            array('id' => '95', 'subarea' => 'Spokane-coeur dAlene - WA', 'default' => true),
            array('id' => '243', 'subarea' => 'Appleton-oshkosh-FDL - WI', 'default' => true),
            array('id' => '241', 'subarea' => 'Green bay - WI', 'default' => true),
            array('id' => '165', 'subarea' => 'Madison - WI', 'default' => true),
        );
    }

}
